name: NodeEmulator Workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Publish application
        run: |
          cd ./prakticka_cast/NodeEmulator
          dotnet publish ./NodeEmulator -r win-x64 -c Release -o ./published-app -p:PublishSingleFile=true --self-contained false

      - name: Display the workspace path
        run: |
            cd ./prakticka_cast/NodeEmulator/published-app
            dir

      - name: upload publish
        uses: actions/upload-artifact@v4
        with:
          name: emulator-exe-artifact
          path: ./prakticka_cast/NodeEmulator/published-app/NodeEmulator.exe