name: Teoretická Část Workflow

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0.x
          
      - name: exe
        run: ./.github/workflows/DocxToMd2_1 -i ${{ github.workspace }}/teoreticka_cast/xnovm288_DP.docx -o ./.github/workflows/output.md

#      - name: test file
#        run: echo "updated at ${{ github.event.repository.updated_at}}" > ./.github/workflows/output.md
      
      - name: upload md
        uses: actions/upload-artifact@v4
        with:
          name: md-artifact
          path: ./.github/workflows/output.md